create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table cast_cast (cast_id integer not null, actor_id integer not null);
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table cast_cast add constraint FKaa6vnsmqs53yk43d0rss70c6f foreign key (actor_id) references actor;
alter table cast_cast add constraint FKkc40vo9rsd4obeb3guxthuuk0 foreign key (cast_id) references cast;
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
create sequence hibernate_sequence start with 1 increment by 1;
create table actor (id integer not null, age integer not null, name varchar(255) not null, primary key (id));
create table cast (id integer not null, primary key (id));
create table movie (id integer not null, cost_to_make double not null, movie_length integer not null, name varchar(30) not null, release_date varchar(255) not null, movie_id integer, primary key (id));
alter table movie add constraint FK46nbfggcqfj4ylrnfc9bsj0ms foreign key (movie_id) references movie;
alter table movie add constraint FKc4wgnlb08qm2frpg8l2p0scpg foreign key (id) references cast;
